version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sakura
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=sakura_genie
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - "3336:3306"     
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:    
