version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=mouse_tracker
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - "3336:3306"     
  backend:
    image: golang:1.13-alpine
    volumes:
      - ./backend:/go/src/backend
    working_dir: /go/src/backend
    links:
      - mysql
    ports:
      - "8080:8080"
    command: go run main.go
